name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
{% raw %}
    runs-on: ${{ matrix.os }}
{% endraw %}
    steps:
    - uses: actions/checkout@v2

{%- if package_manager == 'poetry' %}
    - name: Install poetry
      run: pipx install poetry
{% endif -%}

{% raw %}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
{% endraw %}
        cache: {% if package_manager == 'poetry' %}poetry{% else %}pip{% endif %}

    - name: Install dependencies
      run: {% if package_manager == 'poetry' %}poetry install{% else %}pip install ".[dev]"{% endif %}
    - name: Run tests
      run: |
        {% if package_manager == 'poetry' %}poetry run {% endif %}xonsh -c "xontrib load {{ project_package_name}}"
        {% if package_manager == 'poetry' %}poetry run {% endif %}pytest
